In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("TMDB_movie_dataset_v11.csv")

In [3]:
df.head(1)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."

In [4]:
df.shape

(1193395, 24)

In [5]:
df.describe()

,id,vote_average,vote_count,revenue,runtime,budget,popularity
count,1.193395e+06,1.193395e+06,1.193395e+06,1.193395e+06,1.193395e+06,1.193395e+06,1.193395e+06
mean,7.729766e+05,1.803083e+00,1.797462e+01,6.758673e+05,4.690958e+01,2.622594e+05,1.199026e+00
std,4.125623e+05,2.986751e+00,3.108701e+02,1.835194e+07,6.153850e+01,5.105051e+06,7.407009e+00
min,2.000000e+00,0.000000e+00,0.000000e+00,-1.200000e+01,-2.800000e+01,0.000000e+00,0.000000e+00
25%,4.278575e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.000000e-01
50%,7.799880e+05,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+01,0.000000e+00,6.000000e-01
75%,1.142720e+06,4.300000e+00,1.000000e+00,0.000000e+00,8.800000e+01,0.000000e+00,8.710000e-01
max,1.449908e+06,1.000000e+01,3.449500e+04,5.000000e+09,1.440000e+04,1.000000e+09,2.994357e+03

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1193395 entries, 0 to 1193394
Data columns (total 24 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1193395 non-null  int64
 1   title                 1193382 non-null  object
 2   vote_average          1193395 non-null  float64
 3   vote_count            1193395 non-null  int64
 4   status                1193395 non-null  object
 5   release_date          981905 non-null   object
 6   revenue               1193395 non-null  int64
 7   runtime               1193395 non-null  int64
 8   adult                 1193395 non-null  bool
 9   backdrop_path         312623 non-null   object
 10  budget                1193395 non-null  int64
 11  homepage              125624 non-null   object
 12  imdb_id               616143 non-null   object
 13  original_language     1193395 non-null  object
 14  original_title        1193382 non-null  object
 15  overview              943757 non-null   object
 16  popularity            1193395 non-null  float64
 17  poster_path           805956 non-null   object
 18  tagline               167127 non-null   object
 19  genres                704682 non-null   object
 20  production_companies  532474 non-null   object
 21  production_countries  653214 non-null   object
 22  spoken_languages      673676 non-null   object
 23  keywords              316480 non-null   object
dtypes: bool(1), float64(2), int64(5), object(16)
memory usage: 210.6+ MB

In [7]:
df['original_language'].value_counts()

original_language
en    646189
fr     69820
es     60814
de     55979
ja     51920
       ...
ts         1
ii         1
rn         1
an         1
kg         1
Name: count, Length: 174, dtype: int64

In [8]:
df_english = df[df['original_language'] == 'en']  
df=df_english.iloc[:5000]

In [9]:
df

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5775,13122,The People Under the Stairs,6.568,584,Released,1991-11-01,31347154,102,False,/lyGRyMxIYwvPObfOYWYDivMQUqh.jpg,...,The People Under the Stairs,"Poindexter ""Fool"" Williams, his brother Leroy,...",17.585,/8OWDBVmGdM7HwaDtbDsdn6Rlzqj.jpg,In every neighborhood there is one house that ...,"Horror, Comedy","Universal Pictures, Alive Films",United States of America,English,"child abuse, escape, shotgun, serial killer, l..."
5777,9445,Apt Pupil,6.530,584,Released,1998-10-23,8863193,107,False,/xQpsxWPaAZW77G1L2Nzi2EAhizZ.jpg,...,Apt Pupil,"One day in 1984, Todd Bowden, a brilliant high...",11.712,/uTQMZLsbpoEYCjnJX8G3CmjCZDg.jpg,"If you don't believe in the existence of evil,...","Drama, Thriller","Bad Hat Harry Productions, Canal+ Droits Audio...","France, United States of America","English, German","high school, based on novel or book, secret id..."
5779,14181,Boiler Room,6.758,584,Released,2000-02-18,28780255,118,False,/3xIzrSM5GKoF8JAlUnnSaG04gCS.jpg,...,Boiler Room,A college dropout gets a job as a broker for a...,17.614,/uYbkko9u3RUbrFO7oDCScxdOlvQ.jpg,Welcome to the new American dream.,"Crime, Drama, Thriller",New Line Cinema,United States of America,"English, Russian","finances, long island, new york, stockbroker, ..."
5780,14534,Rudy,7.381,584,Released,1993-09-17,22750363,114,False,/flzoI6jEw7J0X5x2rwOMZCwZ57I.jpg,...,Rudy,Rudy grew up in a steel mill town where most p...,17.902,/fAbfTCRpjHe2rprXBly55KL1dL9.jpg,"It's not the size of the dog in the fight, It'...","Drama, History",TriStar Pictures,United States of America,"Spanish, English","underdog, sports, american football, biography..."
5782,11708,Chitty Chitty Bang Bang,6.775,583,Released,1968-12-17,0,144,False,/vOl8p3u3MKjACtpTn6CV3BB7HY.jpg,...,Chitty Chitty Bang Bang,A hapless inventor finally finds success with ...,17.482,/mfbEh3P2h26BriPIjqnEjwWeWFu.jpg,The most fantasmagorical musical entertainment...,"Family, Music, Adventure, Fantasy, Comedy","United Artists, Dramatic Features, Warfield",United Kingdom,"English, Russian","flying car, inventor, oldtimer, steampunk, ben..."

In [10]:
#genres
#id
#keywords
#title
#overview
#production_companies

df=df[['id','title','overview','genres','keywords','production_companies']]

In [11]:
df

,id,title,overview,genres,keywords,production_companies
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...","Legendary Pictures, Syncopy, Warner Bros. Pict..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...","Legendary Pictures, Syncopy, Lynda Obst Produc..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...","DC Comics, Legendary Pictures, Syncopy, Isobel..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...","Dune Entertainment, Lightstorm Entertainment, ..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",Marvel Studios
...,...,...,...,...,...,...
5775,13122,The People Under the Stairs,"Poindexter ""Fool"" Williams, his brother Leroy,...","Horror, Comedy","child abuse, escape, shotgun, serial killer, l...","Universal Pictures, Alive Films"
5777,9445,Apt Pupil,"One day in 1984, Todd Bowden, a brilliant high...","Drama, Thriller","high school, based on novel or book, secret id...","Bad Hat Harry Productions, Canal+ Droits Audio..."
5779,14181,Boiler Room,A college dropout gets a job as a broker for a...,"Crime, Drama, Thriller","finances, long island, new york, stockbroker, ...",New Line Cinema
5780,14534,Rudy,Rudy grew up in a steel mill town where most p...,"Drama, History","underdog, sports, american football, biography...",TriStar Pictures
5782,11708,Chitty Chitty Bang Bang,A hapless inventor finally finds success with ...,"Family, Music, Adventure, Fantasy, Comedy","flying car, inventor, oldtimer, steampunk, ben...","United Artists, Dramatic Features, Warfield"

In [12]:
df.head()

,id,title,overview,genres,keywords,production_companies
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...","Legendary Pictures, Syncopy, Warner Bros. Pict..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...","Legendary Pictures, Syncopy, Lynda Obst Produc..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...","DC Comics, Legendary Pictures, Syncopy, Isobel..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...","Dune Entertainment, Lightstorm Entertainment, ..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",Marvel Studios

In [17]:
df.isnull().sum()

id                      0
title                   0
overview                0
genres                  0
keywords                0
production_companies    0
dtype: int64

In [14]:
df.dropna(subset=['production_companies'])

,id,title,overview,genres,keywords,production_companies
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...","Legendary Pictures, Syncopy, Warner Bros. Pict..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...","Legendary Pictures, Syncopy, Lynda Obst Produc..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...","DC Comics, Legendary Pictures, Syncopy, Isobel..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...","Dune Entertainment, Lightstorm Entertainment, ..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",Marvel Studios
...,...,...,...,...,...,...
5775,13122,The People Under the Stairs,"Poindexter ""Fool"" Williams, his brother Leroy,...","Horror, Comedy","child abuse, escape, shotgun, serial killer, l...","Universal Pictures, Alive Films"
5777,9445,Apt Pupil,"One day in 1984, Todd Bowden, a brilliant high...","Drama, Thriller","high school, based on novel or book, secret id...","Bad Hat Harry Productions, Canal+ Droits Audio..."
5779,14181,Boiler Room,A college dropout gets a job as a broker for a...,"Crime, Drama, Thriller","finances, long island, new york, stockbroker, ...",New Line Cinema
5780,14534,Rudy,Rudy grew up in a steel mill town where most p...,"Drama, History","underdog, sports, american football, biography...",TriStar Pictures
5782,11708,Chitty Chitty Bang Bang,A hapless inventor finally finds success with ...,"Family, Music, Adventure, Fantasy, Comedy","flying car, inventor, oldtimer, steampunk, ben...","United Artists, Dramatic Features, Warfield"

In [15]:
df = df.copy() 
df.fillna('unknown', inplace=True)

In [16]:
df.iloc[0].genres

'Action, Science Fiction, Adventure'

In [18]:
df.iloc[0].keywords

'rescue, mission, dream, airplane, paris, france, virtual reality, kidnapping, philosophy, spy, allegory, manipulation, car crash, heist, memory, architecture, los angeles, california, dream world, subconscious'

In [19]:
df.iloc[0].production_companies

'Legendary Pictures, Syncopy, Warner Bros. Pictures'

In [20]:
df['overview'][0]

'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.'

In [21]:
df['genres'] = df['genres'].apply(lambda x: x.split(","))
df['keywords'] = df['keywords'].apply(lambda x: x.split(","))
df['overview'] = df['overview'].apply(lambda x: x.split(","))
df['production_companies'] = df['production_companies'].apply(lambda x: x.split(","))

In [22]:
df.head()

,id,title,overview,genres,keywords,production_companies
0,27205,Inception,"[Cobb, a skilled thief who commits corporate ...","[Action, Science Fiction, Adventure]","[rescue, mission, dream, airplane, paris, ...","[Legendary Pictures, Syncopy, Warner Bros. P..."
1,157336,Interstellar,[The adventures of a group of explorers who ma...,"[Adventure, Drama, Science Fiction]","[rescue, future, spacecraft, race against t...","[Legendary Pictures, Syncopy, Lynda Obst Pro..."
2,155,The Dark Knight,[Batman raises the stakes in his war on crime....,"[Drama, Action, Crime, Thriller]","[joker, sadism, chaos, secret identity, cr...","[DC Comics, Legendary Pictures, Syncopy, Is..."
3,19995,Avatar,"[In the 22nd century, a paraplegic Marine is ...","[Action, Adventure, Fantasy, Science Fiction]","[future, society, culture clash, space trav...","[Dune Entertainment, Lightstorm Entertainment..."
4,24428,The Avengers,[When an unexpected enemy emerges and threaten...,"[Science Fiction, Action, Adventure]","[new york city, superhero, shield, based on...",[Marvel Studios]

In [23]:
df['genres']=df['genres'].apply(lambda x:[i.replace(" ","")for i in x])
df['keywords']=df['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
df['production_companies']=df['production_companies'].apply(lambda x:[i.replace(" ","")for i in x])

In [24]:
df.head()

,id,title,overview,genres,keywords,production_companies
0,27205,Inception,"[Cobb, a skilled thief who commits corporate ...","[Action, ScienceFiction, Adventure]","[rescue, mission, dream, airplane, paris, fran...","[LegendaryPictures, Syncopy, WarnerBros.Pictures]"
1,157336,Interstellar,[The adventures of a group of explorers who ma...,"[Adventure, Drama, ScienceFiction]","[rescue, future, spacecraft, raceagainsttime, ...","[LegendaryPictures, Syncopy, LyndaObstProducti..."
2,155,The Dark Knight,[Batman raises the stakes in his war on crime....,"[Drama, Action, Crime, Thriller]","[joker, sadism, chaos, secretidentity, crimefi...","[DCComics, LegendaryPictures, Syncopy, IsobelG..."
3,19995,Avatar,"[In the 22nd century, a paraplegic Marine is ...","[Action, Adventure, Fantasy, ScienceFiction]","[future, society, cultureclash, spacetravel, s...","[DuneEntertainment, LightstormEntertainment, 2..."
4,24428,The Avengers,[When an unexpected enemy emerges and threaten...,"[ScienceFiction, Action, Adventure]","[newyorkcity, superhero, shield, basedoncomic,...",[MarvelStudios]

In [25]:
df['tags']=df['overview']+df['genres']+df['keywords']+df['production_companies']

In [26]:
df.head()

,id,title,overview,genres,keywords,production_companies,tags
0,27205,Inception,"[Cobb, a skilled thief who commits corporate ...","[Action, ScienceFiction, Adventure]","[rescue, mission, dream, airplane, paris, fran...","[LegendaryPictures, Syncopy, WarnerBros.Pictures]","[Cobb, a skilled thief who commits corporate ..."
1,157336,Interstellar,[The adventures of a group of explorers who ma...,"[Adventure, Drama, ScienceFiction]","[rescue, future, spacecraft, raceagainsttime, ...","[LegendaryPictures, Syncopy, LyndaObstProducti...",[The adventures of a group of explorers who ma...
2,155,The Dark Knight,[Batman raises the stakes in his war on crime....,"[Drama, Action, Crime, Thriller]","[joker, sadism, chaos, secretidentity, crimefi...","[DCComics, LegendaryPictures, Syncopy, IsobelG...",[Batman raises the stakes in his war on crime....
3,19995,Avatar,"[In the 22nd century, a paraplegic Marine is ...","[Action, Adventure, Fantasy, ScienceFiction]","[future, society, cultureclash, spacetravel, s...","[DuneEntertainment, LightstormEntertainment, 2...","[In the 22nd century, a paraplegic Marine is ..."
4,24428,The Avengers,[When an unexpected enemy emerges and threaten...,"[ScienceFiction, Action, Adventure]","[newyorkcity, superhero, shield, basedoncomic,...",[MarvelStudios],[When an unexpected enemy emerges and threaten...

In [27]:
new_df=df[['id','title','tags']]

In [28]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\priti\AppData\Local\Temp\ipykernel_22108\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [29]:
new_df.head()

       id            title                                               tags
0   27205        Inception  Cobb  a skilled thief who commits corporate es...
1  157336     Interstellar  The adventures of a group of explorers who mak...
2     155  The Dark Knight  Batman raises the stakes in his war on crime. ...
3   19995           Avatar  In the 22nd century  a paraplegic Marine is di...
4   24428     The Avengers  When an unexpected enemy emerges and threatens...

In [30]:
new_df['tags'][0]

'Cobb  a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception"  the implantation of another person\'s idea into a target\'s subconscious. Action ScienceFiction Adventure rescue mission dream airplane paris france virtualreality kidnapping philosophy spy allegory manipulation carcrash heist memory architecture losangeles california dreamworld subconscious LegendaryPictures Syncopy WarnerBros.Pictures'

In [31]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\priti\AppData\Local\Temp\ipykernel_22108\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [32]:
new_df.head()

       id            title                                               tags
0   27205        Inception  cobb  a skilled thief who commits corporate es...
1  157336     Interstellar  the adventures of a group of explorers who mak...
2     155  The Dark Knight  batman raises the stakes in his war on crime. ...
3   19995           Avatar  in the 22nd century  a paraplegic marine is di...
4   24428     The Avengers  when an unexpected enemy emerges and threatens...

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [34]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [35]:
cv.fit_transform(new_df['tags']).toarray().shape

(5000, 5000)

In [36]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [37]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [38]:
cv.get_feature_names_out()

array(['000', '0entertainment', '10', ..., 'zombies', 'zone', 'zoo'],
      dtype=object)

In [39]:
cv.get_feature_names_out().tolist()

['000',
 '0entertainment',
 '10',
 '11',
 '12',
 '13',
 '14',
 '1453',
 '1492pictures',
 '15',
 '15thcentury',
 '16',
 '16thcentury',
 '17',
 '17thcentury',
 '18th',
 '18thcentury',
 '19',
 '1900s',
 '1910s',
 '1920s',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1962',
 '1970s',
 '1973',
 '1980s',
 '1988',
 '1990s',
 '19th',
 '19thcentury',
 '20',
 '2000s',
 '2001',
 '2010s',
 '2030s',
 '2040s',
 '20th',
 '20thcenturyfox',
 '20thcenturyfoxanimation',
 '20thcenturystudios',
 '21lapsentertainment',
 '24',
 '25',
 '2929productions',
 '30',
 '3artsentertainment',
 '40',
 '40acresandamulefilmworks',
 '476',
 '50',
 'a24',
 'aardman',
 'aaron',
 'abandapart',
 'abandoned',
 'abducted',
 'abduction',
 'abilities',
 'ability',
 'able',
 'aboard',
 'absurd',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'accomplished',
 'account',
 'accountant',
 'accused',
 'ace',
 'act',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'actor',
 'actors',
 'actress',
 'acts',
 'actually',
 'ad',
 'adam',
 'adaptation',
 'addict',
 'addiction',
 'admiring',
 'adolescence',
 'adopted',
 'adoption',
 'adopts',
 'adoring',
 'adrenaline',
 'adult',
 'adultanimation',
 'adultery',
 'adulthood',
 'adults',
 'advanced',
 'adventure',
 'adventurer',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affinity',
 'afghanistan',
 'africa',
 'african',
 'africanamericanhistory',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airforce',
 'airplane',
 'airplanecrash',
 'airport',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alconentertainment',
 'alex',
 'alexander',
 'alice',
 'alien',
 'alieninfection',
 'alieninvasion',
 'alienlife',
 'alienplanet',
 'aliens',
 'alike',
 'alive',
 'alliance',
 'alliancefilms',
 'allied',
 'allies',
 'alligator',
 'allow',
 'allowed',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpha',
 'alphavillefilms',
 'alpsmountains',
 'alter',
 'altered',
 'alterego',
 'alternate',
 'alternatedimension',
 'alternatereality',
 'alzheimer',
 'amanda',
 'amazing',
 'amazon',
 'amazonrainforest',
 'amazonstudios',
 'ambassador',
 'ambition',
 'ambitions',
 'ambitious',
 'amblinentertainment',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americandream',
 'americanempiricalpictures',
 'americanfootball',
 'americans',
 'americanzoetrope',
 'amid',
 'amnesia',
 'amsterdam',
 'amused',
 'amusement',
 'amusementpark',
 'amy',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientegypt',
 'ancientgreece',
 'ancientrome',
 'ancientworld',
 'andrew',
 'android',
 'andy',
 'angel',
 'angeles',
 'anger',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animallogic',
 'animals',
 'animated',
 'animatedscene',
 'animation',
 'ann',
 'anna',
 'annapurnapictures',
 'anne',
 'annie',
 'announces',
 'annual',
 'anonymity',
 'anonymous',
 'anonymouscontent',
 'answer',
 'answers',
 'ant',
 'antarctica',
 'anthology',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antiwar',
 'antoncapitalentertainment',
 'anxious',
 'apart',
 'apartment',
 'apatowproductions',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apocalypticfuture',
 'apparent',
 'appear',
 'appears',
 'appianway',
 'apple',
 'apprentice',
 'approach',
 'approached',
 'approaching',
 'april',
 'arab',
 'aradproductions',
 'archaeologist',
 'archeology',
 'archer',
 'architect',
 'area',
 'arena',
 'argument',
 'ariel',
 'aristocrat',
 'arizona',
 'arkansas',
 'armed',
 'arms',
 'armsdealer',
 'army',
 'arrangedmarriage',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'arson',
 'art',
 'arte',
 'artefrancecinÃ©ma',
 'arthur',
 'artificial',
 'artificialintelligence',
 'artisanentertainment',
 'artist',
 'artists',
 'arts',
 'asia',
 'asianamerican',
 'aside',
 'ask',
 'asked',
 'asks',
 'aspiring',
 'aspiringactor',
 'assassin',
 'assassinate',
 'assassination',
 'assassinationattempt',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistant',
 'associates',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'atlanta',
 'atlantis',
 'atlasentertainment',
 'atmosphereentertainmentmm',
 'atomicbomb',
 'atomicmonster',
 'atresmedia',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attemptedmurder',
 'attempting',
 'attempts',
 'attend',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attraction',
 'attractive',
 'audition',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'author',
 'authorities',
 'autism',
 'automatikentertainment',
 'avenge',
 'avengers',
 'average',
 'averypix',
 'avoid',
 'avoiding',
 'await',
 'awaits',
 'awakening',
 'awakens',
 'award',
 'away',
 'awkward',
 'awry',
 'ax',
 'babe',
 'baby',
 'babysitter',
 'bachelor',
 'backdrop',
 'backwoods',
 'bad',
 'badhatharryproductions',
 'badly',
 'badrobot',
 'bahamas',
 'baker',
 'balance',
 'ballet',
 'baltimore',
 'baltimorepictures',
 'band',
 'bangkok',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'banks',
 'bar',
 'barbie',
 'barely',
 'bargained',
 'barn',
 'barney',
 'baron',
 'barry',
 'bars',
 'bartender',
 'base',
 'baseball',
 'based',
 'basedoncartoon',
 'basedonchildren',
 'basedoncomic',
 'basedonfairytale',
 'basedongraphicnovel',
 'basedonmagazine',
 'basedonmanga',
 'basedonmemoirorautobiography',
 'basedonmovie',
 'basedonmyths',
 'basedonnovelorbook',
 'basedonplayormusical',
 'basedonshortfilm',
 'basedonshortstory',
 'basedontoy',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'bathtub',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'bbcfilm',
 'bdsm',
 'beach',
 'beaconpictures',
 'bear',
 'beast',
 'beat',
 'beating',
 'beautiful',
 'beauty',
 'becominganadult',
 'bed',
 'bedfordfallsproductions',
 'bee',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'belle',
 'beloved',
 'ben',
 'benderspink',
 'beneath',
 'benedict',
 'benjamin',
 'bennett',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriends',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bets',
 'better',
 'beverly',
 'bfi',
 'bible',
 'bid',
 'big',
 'bigbeach',
 'biggest',
 'bigindiepictures',
 'bigscreenproductions',
 'bigtalkproductions',
 'biker',
 'bikini',
 'billion',
 'billionaire',
 'billy',
 'biography',
 'biological',
 'biologicalweapon',
 'bird',
 'birth',
 'birthday',
 'birthdayparty',
 'bisexuality',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackandwhite',
 'blackbearpictures',
 'blackhumor',
 'blacklabelmedia',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blade',
 'blair',
 'blind',
 'blindingedgepictures',
 'blindnessandimpairedvision',
 'blizzard',
 'block',
 'blonde',
 'blood',
 'bloodthirsty',
 'bloody',
 'bloom',
 'blown',
 'blue',
 'bluegrassfilms',
 'blueprintpictures',
 'blues',
 'blueskystudios',
 'blumhouseproductions',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bodies',
 'body',
 'bodyguard',
 'bodyhorror',
 'bold',
 'boldfilms',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'boobytrap',
 'book',
 'books',
 'bookstore',
 'border',
 'bored',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'bounty',
 'bountyhunter',
 'bourne',
 'bowandarrow',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boyfriendex',
 'boyfriendgirlfriendrelationship',
 'boys',
 'brad',
 'brain',
 'brand',
 'brandenburg',
 'brandywineproductions',
 'bratva',
 'brave',
 'bravery',
 'break',
 'breakdown',
 'breaking',
 'breakingthefourthwall',
 'breaks',
 'brian',
 'bride',
 'bridge',
 'briefcase',
 'bright',
 'brightlightpictures',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britisharmy',
 'britishmonarchy',
 'britishsecretservice',
 'britishspy',
 'broadway',
 'broke',
 'broken',
 'brokenroadproductions',
 'broker',
 'bronstudios',
 'brooklyn',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brutal',
 'brutality',
 'brutally',
 'brutalviolence',
 'buck',
 'budapest',
 'buddies',
 'buddy',
 'buddycomedy',
 'buddycop',
 'buenavistainternational',
 'bugs',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunker',
 'bunny',
 'burglar',
 'buried',
 'burned',
 'bus',
 'business',
 'businessman',
 'busy',
 'butcher',
 'butler',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'california',
 'called',
 'calls',
 'calvin',
 'came',
 'camera',
 'camp',
 'campaign',
 'campbellgrobmanfilms',
 'camping',
 'campus',
 'canada',
 'canal',
 'cancer',
 'cannibal',
 'cannongroup',
 'capable',
 'caper',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'car',
 'caraccident',
 'carbomb',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caregiver',
 'caretaker',
 'caribbeansea',
 'carl',
 'carnival',
 'carol',
 'carolcopictures',
 'carolina',
 'carpenter',
 'carrace',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'case',
 'casey',
 'cash',
 'casino',
 'cast',
 'castle',
 'castlerockentertainment',
 'casual',
 'cat',
 'cataclysm',
 'catastrophe',
 'catastrophic',
 'catch',
 'catches',
 'catholic',
 'catholicchurch',
 'catholicism',
 'caught',
 'cause',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'cbsfilms',
 'celebration',
 'celebrity',
 'cell',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'central',
 'centralpark',
 'centropolisentertainment',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'chaos',
 'chaotic',
 'character',
 'characters',
 'characterstudy',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chauffeur',
 'cheating',
 'cheerleader',
 'cheese',
 'chef',
 'chemical',
 'cherninentertainment',
 'cheyenneenterprises',
 'chicago',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'childhoodfriends',
 'childhoodtrauma',
 'childkidnapping',
 'childmurder',
 'childprodigy',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chris',
 'christian',
 'christianity',
 'christine',
 'christmas',
 'christmaseve',
 'christmasparty',
 'christmastree',
 'christopher',
 'chronicle',
 'chuck',
 'church',
 'cia',
 'cigarette',
 'cinderella',
 'cinÃ©',
 'circle',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilrights',
 'civilwar',
 'claim',
 'claiming',
 'claims',
 'claire',
 'clan',
 'clark',
 'clash',
 'class',
 'classdifferences',
 'classic',
 'classmate',
 'classroom',
 'claus',
 'claustrophobia',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clique',
 'clock',
 'clone',
 'close',
 'closer',
 'closest',
 'closesttotheholeproductions',
 'closing',
 'cloud',
 'clown',
 'club',
 'clue',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'cocky',
 'code',
 'col',
 'cold',
 'coldwar',
 'cole',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collegestudent',
 'collide',
 'collision',
 'colonel',
 'colony',
 'colorado',
 'colorforce',
 'colorful',
 'columbiapictures',
 'coma',
 'combat',
 'come',
 'comeback',
 'comedian',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comicbook',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commando',
 'commit',
 'commitment',
 'committed',
 'common',
 'communism',
 'community',
 'companion',
 'companions',
 'company',
 'compete',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'conartist',
 'concert',
 'confession',
 'confidence',
 'conflict',
 'confront',
 'confronted',
 'congress',
 'conman',
 'connected',
 'connecticut',
 'connection',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'conspiracy',
 'constantinfilm',
 'construction',
 'contact',
 'contend',
 'contest',
 'continue',
 'continues',
 'contraband',
 'contract',
 'contrafilm',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'cosmic',
 'cost',
 'couldn',
 'count',
 'countdown',
 'countless',
 'country',
 'countryside',
 'county',
 'coup',
 ...]

In [41]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: click in c:\users\priti\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\priti\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.4.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2024.11.6-cp312-cp312-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in c:\users\priti\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\priti\appdata\local\programs\python\python312\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.5 MB 2.6 MB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 2.0 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp312-cp312-win_amd64.whl (273 kB)
Installing collected packages: regex, nltk
Successfully installed nltk-3.9.1 regex-2024.11.6

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [42]:
import nltk

In [43]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [44]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [45]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\priti\AppData\Local\Temp\ipykernel_22108\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [46]:
new_df

,id,title,tags
0,27205,Inception,cobb a skill thief who commit corpor espionag ...
1,157336,Interstellar,the adventur of a group of explor who make use...
2,155,The Dark Knight,batman rais the stake in hi war on crime. with...
3,19995,Avatar,in the 22nd centuri a parapleg marin is dispat...
4,24428,The Avengers,when an unexpect enemi emerg and threaten glob...
...,...,...,...
5775,13122,The People Under the Stairs,"poindext ""fool"" william hi brother leroy and t..."
5777,9445,Apt Pupil,one day in 1984 todd bowden a brilliant high s...
5779,14181,Boiler Room,a colleg dropout get a job as a broker for a s...
5780,14534,Rudy,rudi grew up in a steel mill town where most p...
5782,11708,Chitty Chitty Bang Bang,a hapless inventor final find success with a f...

In [49]:
cv.get_feature_names_out()

array(['000', '0entertainment', '10', ..., 'zombies', 'zone', 'zoo'],
      dtype=object)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [53]:
similarity=cosine_similarity(vectors)

In [51]:
cosine_similarity(vectors).shape

(5000, 5000)

In [54]:
similarity

array([[1.        , 0.15042366, 0.10118058, ..., 0.        , 0.        ,
        0.03504998],
       [0.15042366, 1.        , 0.05631383, ..., 0.03498557, 0.05155393,
        0.0325128 ],
       [0.10118058, 0.05631383, 1.        , ..., 0.1129565 , 0.02080626,
        0.02624319],
       ...,
       [0.        , 0.03498557, 0.1129565 , ..., 1.        , 0.03877834,
        0.0489116 ],
       [0.        , 0.05155393, 0.02080626, ..., 0.03877834, 1.        ,
        0.        ],
       [0.03504998, 0.0325128 , 0.02624319, ..., 0.0489116 , 0.        ,
        1.        ]])

In [67]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(346, np.float64(0.26155718717359333)),
 (817, np.float64(0.22147019900891643)),
 (3178, np.float64(0.2152488010002526)),
 (1832, np.float64(0.21369687880543226)),
 (387, np.float64(0.213352298825066))]

In [74]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [76]:
recommend('Batman Begins')

Batman: Under the Red Hood
The Dark Knight
Batman
Batman: Bad Blood
The Dark Knight Rises

In [72]:
new_df.iloc[1146].title

'Predators'

In [77]:
import pickle

In [78]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [80]:
new_df['title'].values

array(['Inception', 'Interstellar', 'The Dark Knight', ..., 'Boiler Room',
       'Rudy', 'Chitty Chitty Bang Bang'], dtype=object)

In [82]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [84]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))